using System.Net;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TeamleadsBackend.Search;

// Reads the site search index generated by landing-main/layouts/index.shellindex.json.
//
// Exactly like BotDataClient, it supports two transports:
//   BOT_DATA_PATH -> local file /opt/teamleads.kz/latest/shell-index.json
//   BOT_DATA_URL  -> HTTP fetch from https://teamleads.kz/shell-index.json with ETag revalidation
public sealed class ShellIndexClient(HttpClient http, IConfiguration cfg, ILogger<ShellIndexClient> log)
{
    private static readonly TimeSpan Ttl = TimeSpan.FromMinutes(15);
    // A failed refresh backs off too. Inline search fires on every keystroke, so
    // without this a broken index url means one 20s fetch per typed character.
    private static readonly TimeSpan FailureBackoff = TimeSpan.FromMinutes(1);
    private static readonly JsonSerializerOptions Json = new() { PropertyNameCaseInsensitive = true };

    private readonly SemaphoreSlim _gate = new(1, 1);
    private IReadOnlyList<IndexEntry>? _cache;
    private DateTimeOffset _nextRefreshAt;
    private string? _etag;

    public async Task<IReadOnlyList<IndexEntry>> GetIndexAsync(CancellationToken ct)
    {
        if (DateTimeOffset.UtcNow < _nextRefreshAt) return _cache ?? [];

        await _gate.WaitAsync(ct);
        try
        {
            if (DateTimeOffset.UtcNow < _nextRefreshAt) return _cache ?? [];
            await RefreshAsync(ct);
            return _cache ?? [];
        }
        finally { _gate.Release(); }
    }

    private async Task RefreshAsync(CancellationToken ct)
    {
        var botDataPath = cfg["BOT_DATA_PATH"];
        try
        {
            if (!string.IsNullOrWhiteSpace(botDataPath))
            {
                var dir = Path.GetDirectoryName(botDataPath) ?? ".";
                var indexPath = Path.Combine(dir, "shell-index.json");
                if (File.Exists(indexPath))
                {
                    await using var stream = File.OpenRead(indexPath);
                    _cache = await JsonSerializer.DeserializeAsync<List<IndexEntry>>(stream, Json, ct);
                }
                else
                {
                    log.LogWarning("shell-index.json not found at {Path}, falling back to HTTP.", indexPath);
                    await FetchOverHttpAsync(ct);
                }
            }
            else
            {
                await FetchOverHttpAsync(ct);
            }

            _nextRefreshAt = DateTimeOffset.UtcNow + Ttl;
            log.LogInformation("Shell search index loaded: {Count} entries.", _cache?.Count ?? 0);
        }
        catch (Exception ex)
        {
            // Serve the previous snapshot (or nothing) rather than throwing: a failed
            // lookup should degrade to "ничего не найдено", not make Telegram redeliver.
            _nextRefreshAt = DateTimeOffset.UtcNow + FailureBackoff;
            log.LogWarning(ex, "Failed to refresh search index; retrying in {Backoff}.", FailureBackoff);
        }
    }

    private async Task FetchOverHttpAsync(CancellationToken ct)
    {
        var botDataUrl = cfg["BOT_DATA_URL"] ?? "https://teamleads.kz/bot-data.json";
        var indexUrl = botDataUrl.Replace("bot-data.json", "shell-index.json", StringComparison.OrdinalIgnoreCase);

        using var req = new HttpRequestMessage(HttpMethod.Get, indexUrl);
        if (_etag is not null) req.Headers.TryAddWithoutValidation("If-None-Match", _etag);

        using var resp = await http.SendAsync(req, ct);
        // 304: the snapshot we hold is current. RefreshAsync stamps the next refresh.
        if (resp.StatusCode == HttpStatusCode.NotModified) return;

        resp.EnsureSuccessStatusCode();
        _etag = resp.Headers.ETag?.Tag;
        _cache = await resp.Content.ReadFromJsonAsync<List<IndexEntry>>(Json, ct);
    }

    public sealed record IndexEntry(
        [property: JsonPropertyName("u")] string Url,
        [property: JsonPropertyName("n")] string Slug,
        [property: JsonPropertyName("t")] string Title,
        [property: JsonPropertyName("s")] string Section,
        [property: JsonPropertyName("b")] string Body);
}
